timeout: 3

/Graphene Kernel
    protocol: limine
    kernel_path: boot():/boot/graphene
    module_path: boot():/boot/init
    module_cmdline: init
    module_path: boot():/boot/kbd
    module_cmdline: kbd
    module_path: boot():/boot/ramfs
    module_cmdline: ramfs
    module_path: boot():/boot/logger
    module_cmdline: logger
    module_path: boot():/boot/devfs
    module_cmdline: devfs
    module_path: boot():/boot/virtioblk
    module_cmdline: virtioblk
    module_path: boot():/boot/fatfs
    module_cmdline: fatfs
    module_path: boot():/boot/shell
    module_cmdline: shell
